# Generated by Django 4.0.6 on 2023-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('ID_Departamento', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('Nome_Departamento', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
    ]
