# Generated by Django 4.0.6 on 2023-05-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20230501_2337'),
    ]

    operations = [
    ]
