# Generated by Django 4.0.6 on 2023-05-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20230501_2337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table=None,
        ),
    ]
