# Generated by Django 4.0.6 on 2023-05-01 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_departamento_table_alter_funcionario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table=None,
        ),
    ]
