# Generated by Django 4.0.6 on 2023-05-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_alter_departamento_table_alter_funcionario_table'),
    ]

    operations = [
    ]
